apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-master-crio-tracing
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: >-
              data:,%5Bcrio.tracing%5D%0Atracing_sampling_rate_per_million%3D999999%0Aenable_tracing%3Dtrue
          mode: 420
          overwrite: true
          path: /etc/crio/crio.conf.d/otel.conf
