apiVersion: machineconfiguration.openshift.io/v1
kind: ContainerRuntimeConfig
metadata:
 name: custom-loglevel
spec:
 machineConfigPoolSelector:
   matchLabels:
     machineconfiguration.openshift.io/mco-built-in: ''
 containerRuntimeConfig:
   logLevel: debug
