---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-alloy
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-alloy
  namespace: grafana-alloy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-alloy
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - pods/log
  - events
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-alloy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-alloy
subjects:
- kind: ServiceAccount
  name: grafana-alloy
  namespace: grafana-alloy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-alloy-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: grafana-alloy
  namespace: grafana-alloy
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-alloy
  name: grafana-alloy
  namespace: grafana-alloy
spec:
  ports:
  - name: grafana-alloy-http-metrics
    port: 12345
    targetPort: 12345
  - name: grafana-alloy-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    name: grafana-alloy
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-alloy
  namespace: grafana-alloy
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: grafana-alloy
  template:
    metadata:
      labels:
        name: grafana-alloy
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - args:
        - run
        - /etc/alloy/config.alloy
        command:
        - /bin/alloy
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: docker.io/grafana/alloy:v1.3.1
        imagePullPolicy: IfNotPresent
        name: grafana-alloy
        ports:
        - containerPort: 12345
          name: http
        - containerPort: 4317
          name: otlp
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/alloy
          name: grafana-alloy
        - mountPath: /var/log/pods
          name: pod-logs
      serviceAccountName: grafana-alloy
      volumes:
      - configMap:
          name: grafana-alloy
        name: grafana-alloy
      - hostPath:
          path: /var/log/pods
          type: Directory
        name: pod-logs
